# Marketing ML Project

## Objectives
* Build a classifier that predicts wheter a person makes less than $50k or more than $50k given 40 demographic and employment related variables
* Create a segmentation model and demonstrate how the resulting groups differ from one another and how your client can use this model for marketing

In [5]:
import pandas as pd
import numpy as np

## Import dataset

In [6]:
# read column headers into a list
with open('TakeHomeProject/census-bureau.columns', 'r') as f:
    columns = [line.strip() for line in f]

# import main data
df = pd.read_csv('TakeHomeProject/census-bureau.data', header=None, names=headers)

# display first few rows
df.head()

,age,class of worker,detailed industry recode,detailed occupation recode,education,wage per hour,enroll in edu inst last wk,marital stat,major industry code,major occupation code,...,country of birth father,country of birth mother,country of birth self,citizenship,own business or self employed,fill inc questionnaire for veteran's admin,veterans benefits,weeks worked in year,year,label
0,73,Not in universe,0,0,High school graduate,0,Not in universe,Widowed,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
1,58,Self-employed-not incorporated,4,34,Some college but no degree,0,Not in universe,Divorced,Construction,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
2,18,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,...,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,- 50000.
3,9,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
4,10,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.

### Notes
* "Not in universe" used; a distinct category rather than "missing" data
* "?" indicates missing data
* "weight indicates relative distribution of people in general population that each record represents due to stratified sampling"
* complex decision boundary -> motivation for gradient boosted decision tree model classification task
* weighted k-means clustering for segmentation task since weights are important in identifying statistically significant segments

## General Pre-processing

In [7]:
# replace "?"
df_clean = df.replace('?', np.nan)

# display first few rows (cleaned)
df_clean.head()

,age,class of worker,detailed industry recode,detailed occupation recode,education,wage per hour,enroll in edu inst last wk,marital stat,major industry code,major occupation code,...,country of birth father,country of birth mother,country of birth self,citizenship,own business or self employed,fill inc questionnaire for veteran's admin,veterans benefits,weeks worked in year,year,label
0,73,Not in universe,0,0,High school graduate,0,Not in universe,Widowed,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.
1,58,Self-employed-not incorporated,4,34,Some college but no degree,0,Not in universe,Divorced,Construction,Precision production craft & repair,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.
2,18,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,Not in universe,...,Vietnam,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,- 50000.
3,9,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.
4,10,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,Not in universe,...,United-States,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.

## Classification Task

In [ ]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

# preprocessing
X_xgb = df.drop(['weight', 'label'], axis=1).copy()
y_xgb = df['label'].apply(lambda x: 1 if '+ 50000' in str(x) else 0)
sample_weights = df['weight']

# use a constant string instead of "?" and "Not in universe" to preserve information
X_xgb = X_xgb.replace(['?', 'Not in universe'], 'NA')

# label encode categorical columns
categorical = X_xgb.select_dtypes(include=['object']).columns
for col in categorical:
    X_xgb[col] = LabelEncoder().fit_transform(X_xgb[col].astype(str))
    
# train

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

## Resources
https://xgboost.readthedocs.io/en/release_3.2.0/tutorials/model.html